const express=require("express")
const router=express.Router()
const adminController=require("../controllers/adminController")
const { isAuthorized } = require("../middlewares/isAuthorized")
const { isAuthenticated } = require("../middlewares/isAuthenticated")
const {permissionList}=require('../utils/constant')
const {addNewRoleValidation,deleteUserAccountValidation,editUserAccountValidation,updateRoleValidator}=require('../middlewares/validators/adminValidator')
const {validationError}=require('../middlewares/validators/validationError')
router.get("/users",isAuthenticated,isAuthorized(permissionList.getAllUsers),adminController.getAllUsers)
router.put("/users",editUserAccountValidation,validationError,isAuthenticated,isAuthorized(permissionList.editUserAccount),adminController.editUserAccount)
router.delete("/users",deleteUserAccountValidation,validationError,isAuthenticated,isAuthorized(permissionList.deleteUserAccount),adminController.deleteUserAccount)
router.get("/permissions",isAuthenticated,isAuthorized(permissionList.getAllPermissions),adminController.getAllPermissions)
router.get("/roles",isAuthenticated,isAuthorized(permissionList.getAllRoles),adminController.getAllRoles)
router.post("/roles",addNewRoleValidation,validationError,isAuthenticated,isAuthorized(permissionList.addNewRole),adminController.addNewRole)
router.put("/roles",updateRoleValidator,validationError,isAuthenticated,adminController.updateRole)
module.exports=router